# Generated by Django 3.2.7 on 2021-10-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20211002_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='salary',
            field=models.DecimalField(decimal_places=4, max_digits=100),
        ),
    ]
