# Generated by Django 3.2.7 on 2021-10-29 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20211029_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=4, max_digits=10)),
                ('imposto', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.person')),
            ],
        ),
    ]
